# Generated by Django 3.2.8 on 2022-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salle',
            name='description',
            field=models.TextField(),
        ),
    ]
