# Generated by Django 3.2.8 on 2022-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0002_auto_20220522_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salle',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
