# Generated by Django 3.2.8 on 2022-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0004_alter_etudiant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cours',
            field=models.ManyToManyField(null=True, to='ressource.Cours'),
        ),
    ]
