# Generated by Django 3.2.8 on 2022-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0006_alter_etudiant_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
