# Generated by Django 3.2.8 on 2022-05-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0008_alter_cours_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='video',
            new_name='vid',
        ),
    ]
