# Generated by Django 3.2.8 on 2022-05-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0009_rename_video_cours_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120, verbose_name='Nom Cours')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cours',
            name='vid',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AddField(
            model_name='cours',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressource.type'),
        ),
    ]
